-- Add more Slovenian gymnasiums to the schools table
insert into public.schools (name, type) values
  -- Ljubljana gymnasiums
  ('Gimnazija Vič', 'Gimnazija'),
  ('Gimnazija Šiška', 'Gimnazija'),
  ('Gimnazija Moste', 'Gimnazija'),
  ('Gimnazija Ledina', 'Gimnazija'),
  ('Gimnazija Poljane', 'Gimnazija'),
  ('Druga gimnazija Maribor', 'Gimnazija'),
  ('Tretja gimnazija Maribor', 'Gimnazija'),
  ('Prva gimnazija Maribor', 'Gimnazija'),
  ('Gimnazija Celje – Center', 'Gimnazija'),
  ('Gimnazija Kranj', 'Gimnazija'),
  ('Gimnazija Novo mesto', 'Gimnazija'),
  ('Gimnazija Koper', 'Gimnazija'),
  ('Gimnazija Ptuj', 'Gimnazija'),
  ('Gimnazija Murska Sobota', 'Gimnazija'),
  ('Gimnazija Velenje', 'Gimnazija'),
  ('Gimnazija Ravne na Koroškem', 'Gimnazija'),
  ('Gimnazija Krško', 'Gimnazija'),
  ('Gimnazija Slovenska Bistrica', 'Gimnazija'),
  ('Gimnazija Jesenice', 'Gimnazija'),
  ('Gimnazija Trbovlje', 'Gimnazija'),
  ('Gimnazija Brežice', 'Gimnazija'),
  ('Gimnazija Škofja Loka', 'Gimnazija'),
  ('Gimnazija Franceta Prešerna Kranj', 'Gimnazija'),
  ('Gimnazija Šentvid', 'Gimnazija'),
  ('Gimnazija Franca Miklošiča Ljutomer', 'Gimnazija'),
  ('Gimnazija Tolmin', 'Gimnazija'),
  ('Gimnazija Izola', 'Gimnazija'),
  ('Gimnazija Nova Gorica', 'Gimnazija'),
  ('Gimnazija Ormož', 'Gimnazija'),
  ('Gimnazija Litija', 'Gimnazija'),
  ('Gimnazija Dravograd', 'Gimnazija'),
  ('Gimnazija Ilirija', 'Gimnazija'),
  ('Gimnazija Jožeta Plečnika', 'Gimnazija'),
  ('Gimnazija Kamnik', 'Gimnazija'),
  ('Gimnazija Želimlje', 'Gimnazija')
ON CONFLICT DO NOTHING;
